[dev]
    command = "npm run start"
    port = 3000
    targetPort = 3001
    publish = "dist/"


[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "netlify/functions"
