[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}

[dev]
    command = "npm run start"
    port = 4000

[dev.environment]
    JSON_SERVER_PORT = "4001"

[[redirects]]
    from = "/api/*"
    to = "http://localhost:4001/:splat"
    status = 200