[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "functions/"

[dev]
    command = "npm run server"
    port = 4001

[dev.environment]
    JSON_SERVER_PORT = "4001"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200