[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "netlify/functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/json-server/:splat"
    status = 200

[[dev]]
    command = "rum run server"

