[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "netlify/functions"
<<<<<<< HEAD

[dev]
    command = "npm run start"
    port = 3000
    targetPort = 3001
    publish = "dist/"

[[functions]]
    name = "json-server"
    path = "api/json-server.js"
=======

[dev]
    command = "npm run server"
>>>>>>> 3a5cae788693cf7a2f5fe04bb28b46ec3d39618a

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/json-server/:splat"
    status = 200


