[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "netlify/functions"

[dev]
    command = "npm run start"
    port = 3000
    targetPort = 3001
    publish = "dist/"

[dev.environment]
    JSON_SERVER_PORT = "4001"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200