[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}
    functions = "netlify/functions"

[dev]
    command = "npm run server"

[[functions]]
    name = "json-server"
    path = "api/json-server.js"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/json-server/:splat"
    status = 200


