[build]
    command = "npm run build"
    publish = "dist"
    branches = { only = ["main"]}

[dev]
    command = "npm start"
    port = 3000
    functions = "server/"

[dev.environment]
    JSON_SERVER_PORT = "4001"

[[redirects]]
    from = "/api/*"
    to = "http://localhost:$JSON_SERVER_PORT/:splat"
    status = 200